apiVersion: v1
kind: Service
metadata:
  name: cassandra-hs
  labels:
    app: cassandra
spec:
  ports:
    - port: 9042
      name: cassandra
  clusterIP: None
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  serviceName: "cassandra-hs"
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 10
      #volumes:
       # - name: config-template
      #    configMap:
      #      name: testcassandra
      #  - name: cassandra-config
     #     emptyDir: {}
     # initContainers:
      #  - name: copy-cassandra-config
       #   image: busybox
          #command: [ 'sh', '-c', 'cp /etc/config-template/* /etc/config/ && chown -R cassandra:cassandra /etc/config' ]
          #command: [ 'sh', '-c', 'cp /etc/config-template/* /etc/config/' ]
         # volumeMounts:
          #  - name: config-template
           #   mountPath: /etc/config-template
           # - name: cassandra-config
           #   mountPath: /etc/config
      containers:
        - name: cassandra
          image: christ00pher/kubernetes-cassandra:1.0
          resources:
            requests:
              memory: "8Gi"
              cpu: "1000m"
            limits:
              memory: "12Gi"
              cpu: "2000m"
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
          volumeMounts:
            - name: cassandra-data
              mountPath: /cassandra_data
            #- name: cassandra-config
            #  mountPath: /etc/cassandra
          env:
            - name: MAX_HEAP_SIZE
              value: 8192M
            - name: HEAP_NEWSIZE
              value: 1024M
            - name: CASSANDRA_SEEDS
              value: "cassandra-0.cassandra-hs.default.svc.cluster.local"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /ready-probe.sh
            initialDelaySeconds: 15
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard-bs"
        resources:
          requests:
            storage: 10Gi