apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-bs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer